# Generated by Django 3.1.1 on 2023-07-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Tanlanma fayli')),
                ('ftype', models.CharField(choices=[('xls', 'Excel fayl'), ('csv', 'CSV fayl'), ('txt', 'txt fayl')], max_length=50, verbose_name='Tanlanma fayli turi')),
                ('header', models.BooleanField(verbose_name='Tanlanma faylida atributlar sarlavhalari mavjudmi?')),
            ],
            options={
                'verbose_name': 'Tanlanma',
                'verbose_name_plural': 'Tanlanmalar',
            },
        ),
    ]
