# Generated by Django 3.1.1 on 2023-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0003_datasets_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasets',
            name='class_column',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasets',
            name='types',
            field=models.TextField(blank=True, null=True),
        ),
    ]
