# Generated by Django 3.1.1 on 2023-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0004_auto_20230707_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasets',
            name='class_column_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasets',
            name='class_column',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sinf alomat maydoni'),
        ),
    ]
