# Generated by Django 3.1.1 on 2023-07-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0006_datasets_contains_nans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasets',
            name='contains_nans',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
