# Generated by Django 3.1.1 on 2023-08-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0007_auto_20230712_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stabilities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissapp.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='Feature_ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankings', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissapp.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('k', models.IntegerField(blank=True, null=True)),
                ('nbayes', models.FloatField()),
                ('knn', models.FloatField()),
                ('svm', models.FloatField()),
                ('random_forest', models.FloatField()),
                ('dtree', models.FloatField()),
                ('lda', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissapp.datasets')),
            ],
        ),
    ]
