# Generated by Django 3.1.1 on 2023-08-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0008_classification_feature_ranking_stability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domination_intervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1', models.TextField()),
                ('interval_count', models.IntegerField()),
                ('intervals', models.TextField()),
                ('membership_values', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissapp.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='Allowability_intervals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1', models.TextField()),
                ('feature2', models.TextField()),
                ('left', models.FloatField()),
                ('right', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissapp.datasets')),
            ],
        ),
    ]
