# Generated by Django 3.1.1 on 2023-08-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0009_allowability_intervals_domination_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowability_intervals',
            name='median1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allowability_intervals',
            name='median2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
