# Generated by Django 3.1.1 on 2024-07-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0010_auto_20230828_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bemorlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('yosh', models.IntegerField()),
                ('pol', models.IntegerField()),
                ('vdnk', models.BigIntegerField()),
                ('qHBsAg', models.BigIntegerField()),
                ('rnk', models.BigIntegerField()),
                ('gemoglabin', models.FloatField()),
                ('eritrotsit', models.FloatField()),
                ('rang', models.FloatField()),
                ('trombosit', models.FloatField()),
                ('sya', models.FloatField()),
                ('monotsit', models.FloatField()),
                ('leykosit', models.FloatField()),
                ('echt', models.FloatField()),
                ('alt', models.FloatField()),
                ('ast', models.FloatField()),
                ('bilurbin', models.FloatField()),
                ('kreatinin', models.FloatField()),
                ('mochevina', models.FloatField()),
                ('uzi', models.IntegerField()),
                ('belok', models.FloatField()),
                ('fibroskan', models.FloatField()),
                ('albumin', models.FloatField()),
                ('pvt', models.IntegerField()),
                ('shf', models.FloatField()),
                ('klass', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
