# Generated by Django 3.1.1 on 2024-07-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0011_bemorlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemorlar',
            name='limfotsit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
