# Generated by Django 3.1.1 on 2024-09-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0013_bemorlar_turi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bemorlar',
            name='rnk',
        ),
        migrations.AddField(
            model_name='bemorlar',
            name='antihcv',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bemorlar',
            name='antihdv',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bemorlar',
            name='rnk_vgd',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bemorlar',
            name='rnk_vgv',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
