# Generated by Django 3.1.1 on 2024-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0014_auto_20240921_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemorlar',
            name='tekshiruv_fayli',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
