# Generated by Django 3.1.1 on 2024-10-04 20:14

import dissapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dissapp', '0015_bemorlar_tekshiruv_fayli'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemorlar',
            name='doktor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='tekshiruv_fayli',
            field=models.FileField(blank=True, null=True, upload_to=dissapp.models.Bemorlar.user_directory_path),
        ),
    ]
