# Generated by Django 3.1.1 on 2024-10-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0016_auto_20241005_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemorlar',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
