# Generated by Django 3.1.1 on 2024-10-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissapp', '0017_bemorlar_izoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemorlar',
            name='albumin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='alt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='antihcv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='antihdv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='ast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='belok',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='bilurbin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='echt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='eritrotsit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='fibroskan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='gemoglabin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='kreatinin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='leykosit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='limfotsit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='mochevina',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='monotsit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='pol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='pvt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='qHBsAg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='rang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='rnk_vgd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='rnk_vgv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='shf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='sya',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='trombosit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='uzi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='vdnk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bemorlar',
            name='yosh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
